name: ci
on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Bundle
        run: ./gradlew bundleRelease

      - name: Upload Bundle to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_KEY }}
          packageName: com.deliveryapp
          releaseFiles: androidApp/build/outputs/apk/bundle/androidApp-release.aab
          track: internal  # Can be 'internal', 'alpha', 'beta', or 'production'
          status: completed  # Can be 'completed', 'draft', or 'halted'
