name: ci
on:
  pull_request:
    branches: [ main ]
  
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: delivery.apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build Bundle
        run: ./gradlew bundleRelease

      - name: Upload Bundle to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_KEY }}
          packageName: com.deliveryapp
          releaseFiles: androidApp/build/outputs/apk/bundle/androidApp-release.aab
          track: internal  # Can be 'internal', 'alpha', 'beta', or 'production'
          status: completed  # Can be 'completed', 'draft', or 'halted'

